cmake_minimum_required(VERSION 3.10)

file(GLOB RHI_VK_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB RHI_VK_HEADERS "*.inc" "*.h" "*.hpp")

add_subdirectory(./helpers)

set(RHI_VK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR} ${VK_HELPERS_INCLUDE_DIRS} PARENT_SCOPE)
set(RHI_VK_SOURCES ${RHI_VK_SOURCES} ${VK_HELPERS_SOURCES} PARENT_SCOPE)
set(RHI_VK_HEADERS ${RHI_VK_HEADERS} ${VK_HELPERS_HEADERS} PARENT_SCOPE)