cmake_minimum_required(VERSION 3.10)

file(GLOB RHI_VK_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB RHI_VK_HEADERS "*.inc" "*.h" "*.hpp")

find_package(Vulkan REQUIRED)

set(RHI_VK_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR} ${Vulkan_INCLUDE_DIRS} ${Vulkan_INCLUDE_DIRS}/Volk PARENT_SCOPE)
set(RHI_VK_SOURCES ${RHI_VK_SOURCES} ${Vulkan_INCLUDE_DIRS}/Volk/volk.c PARENT_SCOPE)
set(RHI_VK_HEADERS ${RHI_VK_HEADERS} ${Vulkan_INCLUDE_DIRS}/Volk/volk.h PARENT_SCOPE)
set(RHI_VK_LIBS ${Vulkan_LIBRARIES} PARENT_SCOPE)

if(SOURCE_GROUP_EXCLUDE_FILES)
    set(SOURCE_GROUP_EXCLUDE_FILES ${SOURCE_GROUP_EXCLUDE_FILES} ${Vulkan_INCLUDE_DIRS}/Volk/volk.c ${Vulkan_INCLUDE_DIRS}/Volk/volk.h PARENT_SCOPE)
endif()
