cmake_minimum_required(VERSION 3.10)

file(GLOB OS_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB OS_HEADERS "*.inc" "*.h" "*.hpp")

set(OS_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR})

if (WIN32)

add_subdirectory(./windows)

set(OS_INCLUDE_DIRS ${OS_INCLUDE_DIRS} ${OS_WINDOWS_INCLUDE_DIRS})
set(OS_SOURCES ${OS_SOURCES} ${OS_WINDOWS_SOURCES})
set(OS_HEADERS ${OS_HEADERS} ${OS_WINDOWS_HEADERS})

endif(WIN32)

set(OS_INCLUDE_DIRS ${OS_INCLUDE_DIRS} PARENT_SCOPE)
set(OS_SOURCES ${OS_SOURCES} PARENT_SCOPE)
set(OS_HEADERS ${OS_HEADERS} PARENT_SCOPE)