cmake_minimum_required(VERSION 3.10)

file(GLOB HAL_DX12_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB HAL_DX12_HEADERS "*.inc" "*.h" "*.hpp")

add_subdirectory(./helpers)

set(HAL_DX12_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR} ${DX12_HELPERS_INCLUDE_DIRS} PARENT_SCOPE)
set(HAL_DX12_SOURCES ${HAL_DX12_SOURCES} ${DX12_HELPERS_SOURCES} PARENT_SCOPE)
set(HAL_DX12_HEADERS ${HAL_DX12_HEADERS} ${DX12_HELPERS_HEADERS} PARENT_SCOPE)