cmake_minimum_required(VERSION 3.10)

file(GLOB RHI_MTL_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB RHI_MTL_HEADERS "*.inc" "*.h" "*.hpp")

add_subdirectory(./helpers)

set(RHI_MTL_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR} ${MTL_HELPERS_INCLUDE_DIRS} PARENT_SCOPE)
set(RHI_MTL_SOURCES ${RHI_MTL_SOURCES} ${MTL_HELPERS_SOURCES} PARENT_SCOPE)
set(RHI_MTL_HEADERS ${RHI_MTL_HEADERS} ${MTL_HELPERS_HEADERS} PARENT_SCOPE)