cmake_minimum_required(VERSION 3.10)

file(GLOB HAL_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB HAL_HEADERS "*.inc" "*.h" "*.hpp")

add_subdirectory(./dx12)

set(HAL_SOURCES ${HAL_SOURCES} ${HAL_DX12_SOURCES})
set(HAL_HEADERS ${HAL_HEADERS} ${HAL_DX12_HEADERS})

set(HAL_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR} ${HAL_DX12_INCLUDE_DIRS} PARENT_SCOPE)
set(HAL_SOURCES ${HAL_SOURCES} PARENT_SCOPE)
set(HAL_HEADERS ${HAL_HEADERS} PARENT_SCOPE)