cmake_minimum_required(VERSION 3.10)

file(GLOB RHI_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB RHI_HEADERS "*.inc" "*.h" "*.hpp")

add_subdirectory(./dx12)
set(RHI_SOURCES ${RHI_SOURCES} ${RHI_DX12_SOURCES})
set(RHI_HEADERS ${RHI_HEADERS} ${RHI_DX12_HEADERS})
set(RHI_INCLUDE_DIRS ${RHI_DX12_INCLUDE_DIRS} ${CMAKE_CURRENT_SOURCE_DIR})
set(RHI_LIBS ${RHI_LIBS} d3d12 dxgi dxcompiler)

if (ENABLE_VULKAN)

add_subdirectory(./vk)

set(RHI_SOURCES ${RHI_SOURCES} ${RHI_VK_SOURCES})
set(RHI_HEADERS ${RHI_HEADERS} ${RHI_VK_HEADERS})
set(RHI_INCLUDE_DIRS ${RHI_INCLUDE_DIRS} ${RHI_VK_INCLUDE_DIRS})
set(RHI_LIBS ${RHI_LIBS} ${RHI_VK_LIBS})

endif(ENABLE_VULKAN)

set(RHI_SOURCES ${RHI_SOURCES} PARENT_SCOPE)
set(RHI_HEADERS ${RHI_HEADERS} PARENT_SCOPE)
set(RHI_INCLUDE_DIRS ${RHI_INCLUDE_DIRS} PARENT_SCOPE)
set(RHI_LIBS ${RHI_LIBS} PARENT_SCOPE)

if(SOURCE_GROUP_EXCLUDE_FILES)
    set(SOURCE_GROUP_EXCLUDE_FILES ${SOURCE_GROUP_EXCLUDE_FILES} PARENT_SCOPE)
endif()