cmake_minimum_required(VERSION 3.10)

file(GLOB RHI_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB RHI_HEADERS "*.inc" "*.h" "*.hpp")

add_subdirectory(./dx12)

set(RHI_SOURCES ${RHI_SOURCES} ${RHI_DX12_SOURCES})
set(RHI_HEADERS ${RHI_HEADERS} ${RHI_DX12_HEADERS})

set(RHI_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR} ${RHI_DX12_INCLUDE_DIRS} PARENT_SCOPE)
set(RHI_SOURCES ${RHI_SOURCES} PARENT_SCOPE)
set(RHI_HEADERS ${RHI_HEADERS} PARENT_SCOPE)