cmake_minimum_required(VERSION 3.10)

file(GLOB CORE_SOURCES "*.asm" "*.cpp" "*.c")
file(GLOB CORE_HEADERS "*.inc" "*.h" "*.hpp")

add_subdirectory(./scene)

set(CORE_INCLUDE_DIRS ${CMAKE_CURRENT_SOURCE_DIR} ${SCENE_INCLUDE_DIRS} PARENT_SCOPE)
set(CORE_SOURCES ${CORE_SOURCES} ${SCENE_SOURCES} PARENT_SCOPE)
set(CORE_HEADERS ${CORE_HEADERS} ${SCENE_HEADERS} PARENT_SCOPE)